manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: urob
      url-base: https://github.com/urob
  projects:
    # https://github.com/zmkfirmware/zmk/pull/1412
    - name: zmk
      remote: urob
      revision: fix-mod-morph
      import: app/west.yml
  self:
    path: config
