#!/usr/bin/env bash

cd /__w/

west build -s zmk/app -b zaphod -d build/zaphod -- -DZMK_CONFIG=/__w/zaphod-config
#west build -s zmk/app -b seeeduino_xiao -d build/zaphod_lite_xiao -- -DZMK_CONFIG="/__w/zaphod-config" -DSHIELD=zaphod_lite
#west build -s zmk/app -b seeeduino_xiao_ble -d build/zaphod_lite_xiao_ble -- -DZMK_CONFIG="/__w/zaphod-config" -DSHIELD=zaphod_lite
